/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
	'/': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Root */
		get: operations['root__get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/health': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Health */
		get: operations['health_api_health_get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/health/deep': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Deep Health Check */
		get: operations['deep_health_check_api_health_deep_get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/connectors': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Get Connectors */
		get: operations['get_connectors_api_v1_connectors_get'];
		put?: never;
		/** Create Connector */
		post: operations['create_connector_api_v1_connectors_post'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/connectors/{connector_id}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Get Connector */
		get: operations['get_connector_api_v1_connectors__connector_id__get'];
		/** Put Connector */
		put: operations['put_connector_api_v1_connectors__connector_id__put'];
		post?: never;
		/** Delete Connector */
		delete: operations['delete_connector_api_v1_connectors__connector_id__delete'];
		options?: never;
		head?: never;
		/** Patch Connector */
		patch: operations['patch_connector_api_v1_connectors__connector_id__patch'];
		trace?: never;
	};
	'/api/v1/pipelines/inspect': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Inspect Pipeline
		 * @description Inspect CI without creating PRs, dispatching workflows, posting comments, or saving state.
		 */
		post: operations['inspect_pipeline_api_v1_pipelines_inspect_post'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/pipelines/observations/{schedule_id}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Get Pipeline Observation
		 * @description Return the last successful observation, not live CI evidence or a merge authorization.
		 */
		get: operations['get_pipeline_observation_api_v1_pipelines_observations__schedule_id__get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/pipeline-runs': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** List Pipeline Runs */
		get: operations['list_pipeline_runs_api_v1_pipeline_runs_get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/pipeline-runs/{run_id}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Get Pipeline Run */
		get: operations['get_pipeline_run_api_v1_pipeline_runs__run_id__get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/pipeline-runs/{run_id}/attempts': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** List Execution Attempts */
		get: operations['list_execution_attempts_api_v1_pipeline_runs__run_id__attempts_get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/pipeline-runs/{run_id}/lease': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		/** Renew Pipeline Run Lease */
		put: operations['renew_pipeline_run_lease_api_v1_pipeline_runs__run_id__lease_put'];
		/** Acquire Pipeline Run Lease */
		post: operations['acquire_pipeline_run_lease_api_v1_pipeline_runs__run_id__lease_post'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/pipeline-runs/{run_id}/lease/release': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Release Pipeline Run Lease */
		post: operations['release_pipeline_run_lease_api_v1_pipeline_runs__run_id__lease_release_post'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/pipeline-runs/{run_id}/attempts/implementation': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Prepare Implementation Attempt
		 * @description Persist an immutable attempt before any external delegation.
		 */
		post: operations['prepare_implementation_attempt_api_v1_pipeline_runs__run_id__attempts_implementation_post'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/projects': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** List Projects */
		get: operations['list_projects_api_v1_projects_get'];
		put?: never;
		/** Create Project */
		post: operations['create_project_api_v1_projects_post'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/projects/templates': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Get Project Templates
		 * @description Versioned starter files for installation in a target repository.
		 */
		get: operations['get_project_templates_api_v1_projects_templates_get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/projects/import_schedule': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Import Project Schedule
		 * @description Atomically adopt a legacy schedule, preserving its trigger, PRs, and history.
		 */
		post: operations['import_project_schedule_api_v1_projects_import_schedule_post'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/projects/{project_id}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Get Project */
		get: operations['get_project_api_v1_projects__project_id__get'];
		/** Update Project */
		put: operations['update_project_api_v1_projects__project_id__put'];
		post?: never;
		/** Delete Project */
		delete: operations['delete_project_api_v1_projects__project_id__delete'];
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/projects/{project_id}/issues/actionable': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Get Actionable Issue
		 * @description Select one actionable Linear issue without changing Linear or GitHub state.
		 */
		get: operations['get_actionable_issue_api_v1_projects__project_id__issues_actionable_get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/projects/{project_id}/runs/acquire': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Acquire Pipeline Run
		 * @description Resume the active run or atomically acquire one actionable Linear issue.
		 */
		post: operations['acquire_pipeline_run_api_v1_projects__project_id__runs_acquire_post'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/projects/{project_id}/check': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Check Project
		 * @description Read GitHub/Linear and verify one current PR run. Does not install CI or dispatch external work.
		 */
		post: operations['check_project_api_v1_projects__project_id__check_post'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/schedule_configs': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Get Schedule Configs */
		get: operations['get_schedule_configs_api_v1_schedule_configs_get'];
		put?: never;
		/** Create Schedule Config */
		post: operations['create_schedule_config_api_v1_schedule_configs_post'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/schedule_configs/{schedule_config_id}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Get Schedule Config */
		get: operations['get_schedule_config_api_v1_schedule_configs__schedule_config_id__get'];
		/** Put Schedule Config */
		put: operations['put_schedule_config_api_v1_schedule_configs__schedule_config_id__put'];
		post?: never;
		/** Delete Schedule Config */
		delete: operations['delete_schedule_config_api_v1_schedule_configs__schedule_config_id__delete'];
		options?: never;
		head?: never;
		/** Patch Schedule Config */
		patch: operations['patch_schedule_config_api_v1_schedule_configs__schedule_config_id__patch'];
		trace?: never;
	};
	'/api/v1/system_configs': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Get System Configs */
		get: operations['get_system_configs_api_v1_system_configs_get'];
		put?: never;
		/** Create System Config */
		post: operations['create_system_config_api_v1_system_configs_post'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/system_configs/{system_config_id}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Get System Config */
		get: operations['get_system_config_api_v1_system_configs__system_config_id__get'];
		/** Put System Config */
		put: operations['put_system_config_api_v1_system_configs__system_config_id__put'];
		post?: never;
		/** Delete System Config */
		delete: operations['delete_system_config_api_v1_system_configs__system_config_id__delete'];
		options?: never;
		head?: never;
		/** Patch System Config */
		patch: operations['patch_system_config_api_v1_system_configs__system_config_id__patch'];
		trace?: never;
	};
	'/api/v1/schedule_jobs': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Get Schedule Jobs */
		get: operations['get_schedule_jobs_api_v1_schedule_jobs_get'];
		put?: never;
		/** Create Schedule Job */
		post: operations['create_schedule_job_api_v1_schedule_jobs_post'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/schedule_jobs/{schedule_job_id}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Get Schedule Job */
		get: operations['get_schedule_job_api_v1_schedule_jobs__schedule_job_id__get'];
		/** Put Schedule Job */
		put: operations['put_schedule_job_api_v1_schedule_jobs__schedule_job_id__put'];
		post?: never;
		/** Delete Schedule Job */
		delete: operations['delete_schedule_job_api_v1_schedule_jobs__schedule_job_id__delete'];
		options?: never;
		head?: never;
		/** Patch Schedule Job */
		patch: operations['patch_schedule_job_api_v1_schedule_jobs__schedule_job_id__patch'];
		trace?: never;
	};
	'/api/v1/dispatchers/trigger': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Trigger Dispatch
		 * @description Called by an external trigger such as Google Cloud Scheduler.
		 *     Processes due schedules using FOR UPDATE SKIP LOCKED to prevent duplicate execution.
		 */
		post: operations['trigger_dispatch_api_v1_dispatchers_trigger_post'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/tasks/specs': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Get Task Specs
		 * @description Retrieve all registered task specifications, optionally filtered by name.
		 */
		get: operations['get_task_specs_api_v1_tasks_specs_get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
}
export type webhooks = Record<string, never>;
export interface components {
	schemas: {
		/** ActionableIssueSelection */
		ActionableIssueSelection: {
			selected: components['schemas']['LinearIssue'] | null;
			/** Inspected Count */
			inspected_count: number;
			/** Actionable Count */
			actionable_count: number;
			/** Blocked Count */
			blocked_count: number;
		};
		/** CheckRequest */
		CheckRequest: {
			/** Pull Number */
			pull_number: number;
		};
		/** ConnectionCheck */
		ConnectionCheck: {
			/**
			 * Checked At
			 * Format: date-time
			 */
			checked_at: string;
			/** Project Revision */
			project_revision: number;
			/** Ready */
			ready: boolean;
			/** Checks */
			checks: components['schemas']['ConnectionCheckItem'][];
			observation?: components['schemas']['PipelineObservation'] | null;
		};
		/** ConnectionCheckItem */
		ConnectionCheckItem: {
			/** Name */
			name: string;
			/**
			 * Status
			 * @enum {string}
			 */
			status: 'passed' | 'failed' | 'skipped';
			/** Detail */
			detail: string;
		};
		/** ConnectorCreate */
		ConnectorCreate: {
			/** Name */
			name: string;
			provider: components['schemas']['ConnectorProvider'];
			/** Config */
			config?: {
				[key: string]: components['schemas']['JsonValue'];
			};
			/**
			 * Enabled
			 * @default true
			 */
			enabled: boolean;
			/** Credentials */
			credentials: {
				[key: string]: components['schemas']['JsonValue'];
			};
		};
		/** ConnectorPatch */
		ConnectorPatch: {
			/** Name */
			name?: string | null;
			/** Config */
			config?: {
				[key: string]: components['schemas']['JsonValue'];
			} | null;
			/** Enabled */
			enabled?: boolean | null;
			/** Credentials */
			credentials?: {
				[key: string]: components['schemas']['JsonValue'];
			};
		};
		/**
		 * ConnectorProvider
		 * @enum {string}
		 */
		ConnectorProvider: 'github' | 'linear';
		/** ConnectorPut */
		ConnectorPut: {
			/** Name */
			name: string;
			provider: components['schemas']['ConnectorProvider'];
			/** Config */
			config?: {
				[key: string]: components['schemas']['JsonValue'];
			};
			/**
			 * Enabled
			 * @default true
			 */
			enabled: boolean;
			/** Credentials */
			credentials: {
				[key: string]: components['schemas']['JsonValue'];
			};
		};
		/** ConnectorRead */
		ConnectorRead: {
			/** Name */
			name: string;
			provider: components['schemas']['ConnectorProvider'];
			/** Config */
			config?: {
				[key: string]: components['schemas']['JsonValue'];
			};
			/**
			 * Enabled
			 * @default true
			 */
			enabled: boolean;
			/**
			 * Created At
			 * Format: date-time
			 */
			created_at: string;
			/**
			 * Updated At
			 * Format: date-time
			 */
			updated_at: string;
			/**
			 * Id
			 * Format: uuid
			 */
			id: string;
			/** Has Credentials */
			has_credentials: boolean;
		};
		/** DeleteResponse */
		DeleteResponse: {
			/**
			 * Success
			 * @default true
			 */
			success: boolean;
			/** Message */
			message?: string | null;
			/**
			 * Identity
			 * @description The identity of the deleted object.
			 */
			identity?: (string | number)[] | string | number | null;
			/**
			 * Representation
			 * @description The string representation of the deleted object.
			 */
			representation?: string | null;
			/**
			 * Meta
			 * @description Additional metadata about the delete operation.
			 */
			meta?: {
				[key: string]: unknown;
			};
		};
		/** DispatchResponse */
		DispatchResponse: {
			/** Dispatched */
			dispatched: number;
		};
		/**
		 * ExecutionAttemptKind
		 * @enum {string}
		 */
		ExecutionAttemptKind: 'implementation' | 'revision';
		/** ExecutionAttemptList */
		ExecutionAttemptList: {
			/** Items */
			items: components['schemas']['ExecutionAttemptRead'][];
			/** Total Count */
			total_count: number;
		};
		/** ExecutionAttemptRead */
		ExecutionAttemptRead: {
			/**
			 * Created At
			 * Format: date-time
			 */
			created_at: string;
			/**
			 * Updated At
			 * Format: date-time
			 */
			updated_at: string;
			/**
			 * Id
			 * Format: uuid
			 */
			id: string;
			/**
			 * Pipeline Run Id
			 * Format: uuid
			 */
			pipeline_run_id: string;
			/** Attempt Number */
			attempt_number: number;
			kind: components['schemas']['ExecutionAttemptKind'];
			state: components['schemas']['ExecutionAttemptState'];
			/** Request Snapshot */
			request_snapshot: {
				[key: string]: unknown;
			};
			/** Request Digest */
			request_digest: string;
			/**
			 * Idempotency Key
			 * Format: uuid
			 */
			idempotency_key: string;
			/** External Correlation Id */
			external_correlation_id: string | null;
			/** External Status */
			external_status: string | null;
			/** Conversation Url */
			conversation_url: string | null;
			/** Started At */
			started_at: string | null;
			/** Finished At */
			finished_at: string | null;
			/** Failure Code */
			failure_code: string | null;
			/** Failure Detail */
			failure_detail: string | null;
		};
		/**
		 * ExecutionAttemptState
		 * @enum {string}
		 */
		ExecutionAttemptState:
			'planned' | 'dispatching' | 'running' | 'suspended' | 'completed' | 'failed';
		/** GitHubProjectConnection */
		GitHubProjectConnection: {
			/** Repository */
			repository: string;
			/**
			 * Github Connector Id
			 * Format: uuid
			 */
			github_connector_id: string;
			verification: components['schemas']['VerificationConfig'];
			/** Template Id */
			template_id?: ('python-uv' | 'node-npm') | null;
		};
		/** HTTPValidationError */
		HTTPValidationError: {
			/** Detail */
			detail?: components['schemas']['ValidationError'][];
		};
		/** ImplementationRequest */
		ImplementationRequest: {
			/**
			 * Version
			 * @default 1
			 * @constant
			 */
			version: 1;
			/** Correlation Marker */
			correlation_marker: string;
			/** Repository */
			repository: string;
			/** Base Branch */
			base_branch: string;
			/** Head Branch */
			head_branch: string;
			issue: components['schemas']['LinearIssue'];
			/** Instructions */
			instructions: string;
		};
		/** ImportScheduleRequest */
		ImportScheduleRequest: {
			/**
			 * Schedule Id
			 * Format: uuid
			 */
			schedule_id: string;
		};
		/** JobSnapshot */
		JobSnapshot: {
			/** Name */
			name: string;
			/** Status */
			status: string;
			/** Conclusion */
			conclusion?: string | null;
			/** Url */
			url?: string | null;
		};
		JsonValue: unknown;
		/** LeaseGrant */
		LeaseGrant: {
			/**
			 * Run Id
			 * Format: uuid
			 */
			run_id: string;
			/** Owner */
			owner: string;
			/**
			 * Token
			 * Format: uuid
			 */
			token: string;
			/**
			 * Expires At
			 * Format: date-time
			 */
			expires_at: string;
			/** Run Revision */
			run_revision: number;
		};
		/** LeaseMutation */
		LeaseMutation: {
			/** Owner */
			owner: string;
			/**
			 * Token
			 * Format: uuid
			 */
			token: string;
			/**
			 * Ttl Seconds
			 * @default 60
			 */
			ttl_seconds: number;
		};
		/** LeaseRequest */
		LeaseRequest: {
			/** Owner */
			owner: string;
			/**
			 * Ttl Seconds
			 * @default 60
			 */
			ttl_seconds: number;
		};
		/** LinearIssue */
		LinearIssue: {
			/**
			 * Id
			 * Format: uuid
			 */
			id: string;
			/** Identifier */
			identifier: string;
			/** Title */
			title: string;
			/** Description */
			description?: string | null;
			/** Priority */
			priority: number;
			/** State Type */
			state_type: string;
			/**
			 * Created At
			 * Format: date-time
			 */
			created_at: string;
			/**
			 * Updated At
			 * Format: date-time
			 */
			updated_at: string;
			/** Url */
			url: string;
			/** Blockers */
			blockers?: components['schemas']['LinearIssueBlocker'][];
		};
		/** LinearIssueBlocker */
		LinearIssueBlocker: {
			/**
			 * Id
			 * Format: uuid
			 */
			id: string;
			/** Identifier */
			identifier: string;
			/** State Type */
			state_type: string;
		};
		/** LinearProjectConnection */
		LinearProjectConnection: {
			/**
			 * Project Id
			 * Format: uuid
			 */
			project_id: string;
			/** Connector Id */
			connector_id?: string | null;
		};
		/** PaginatedList[ConnectorRead] */
		PaginatedList_ConnectorRead_: {
			/** Items */
			items: components['schemas']['ConnectorRead'][];
			/** Total Count */
			total_count?: number | null;
			/**
			 * Offset
			 * @default 0
			 */
			offset: number;
			/** Limit */
			limit?: number | null;
			/**
			 * Last
			 * @description Check if the current page is the last page
			 */
			readonly last: boolean | null;
			/** First */
			readonly first: boolean;
		};
		/** PaginatedList[ScheduleConfigRead] */
		PaginatedList_ScheduleConfigRead_: {
			/** Items */
			items: components['schemas']['ScheduleConfigRead'][];
			/** Total Count */
			total_count?: number | null;
			/**
			 * Offset
			 * @default 0
			 */
			offset: number;
			/** Limit */
			limit?: number | null;
			/**
			 * Last
			 * @description Check if the current page is the last page
			 */
			readonly last: boolean | null;
			/** First */
			readonly first: boolean;
		};
		/** PaginatedList[ScheduleJobRead] */
		PaginatedList_ScheduleJobRead_: {
			/** Items */
			items: components['schemas']['ScheduleJobRead'][];
			/** Total Count */
			total_count?: number | null;
			/**
			 * Offset
			 * @default 0
			 */
			offset: number;
			/** Limit */
			limit?: number | null;
			/**
			 * Last
			 * @description Check if the current page is the last page
			 */
			readonly last: boolean | null;
			/** First */
			readonly first: boolean;
		};
		/** PaginatedList[SystemConfigRead] */
		PaginatedList_SystemConfigRead_: {
			/** Items */
			items: components['schemas']['SystemConfigRead'][];
			/** Total Count */
			total_count?: number | null;
			/**
			 * Offset
			 * @default 0
			 */
			offset: number;
			/** Limit */
			limit?: number | null;
			/**
			 * Last
			 * @description Check if the current page is the last page
			 */
			readonly last: boolean | null;
			/** First */
			readonly first: boolean;
		};
		/** PipelineObservation */
		PipelineObservation: {
			/**
			 * Kind
			 * @default pipeline_observation
			 * @constant
			 */
			kind: 'pipeline_observation';
			/**
			 * Observed At
			 * Format: date-time
			 */
			observed_at: string;
			config: components['schemas']['PipelineObservationConfig'];
			/** Pulls */
			pulls: components['schemas']['PullObservation'][];
		};
		/**
		 * PipelineObservationConfig
		 * @description One repo/project connection and an explicit, bounded set of PRs to observe.
		 */
		PipelineObservationConfig: {
			/** Repository */
			repository: string;
			/** Linear Project Id */
			linear_project_id?: string | null;
			/**
			 * Github Connector Id
			 * Format: uuid
			 */
			github_connector_id: string;
			/** Pull Numbers */
			pull_numbers: number[];
			verification: components['schemas']['VerificationConfig'];
		};
		/** PipelineRunAcquisition */
		PipelineRunAcquisition: {
			run: components['schemas']['PipelineRunRead'] | null;
			/** Created */
			created: boolean;
			selection?: components['schemas']['ActionableIssueSelection'] | null;
		};
		/** PipelineRunList */
		PipelineRunList: {
			/** Items */
			items: components['schemas']['PipelineRunRead'][];
			/** Total Count */
			total_count: number;
		};
		/** PipelineRunRead */
		PipelineRunRead: {
			/**
			 * Created At
			 * Format: date-time
			 */
			created_at: string;
			/**
			 * Updated At
			 * Format: date-time
			 */
			updated_at: string;
			/**
			 * Id
			 * Format: uuid
			 */
			id: string;
			/**
			 * Project Id
			 * Format: uuid
			 */
			project_id: string;
			/** Project Revision */
			project_revision: number;
			/**
			 * Linear Issue Id
			 * Format: uuid
			 */
			linear_issue_id: string;
			/** Linear Issue Identifier */
			linear_issue_identifier: string;
			linear_issue_snapshot: components['schemas']['LinearIssue'];
			state: components['schemas']['PipelineRunState'];
			/** Pause Reason */
			pause_reason: string | null;
			/** Branch */
			branch: string;
			/** Pull Number */
			pull_number: number | null;
			/** Pull Url */
			pull_url: string | null;
			/** Revision */
			revision: number;
			/** Lease Owner */
			lease_owner: string | null;
			/** Lease Expires At */
			lease_expires_at: string | null;
		};
		/**
		 * PipelineRunState
		 * @enum {string}
		 */
		PipelineRunState:
			| 'queued'
			| 'dispatching'
			| 'implementing'
			| 'awaiting_ci'
			| 'paused'
			| 'completed'
			| 'failed'
			| 'canceled';
		/** PrepareImplementationAttempt */
		PrepareImplementationAttempt: {
			/** Owner */
			owner: string;
			/**
			 * Token
			 * Format: uuid
			 */
			token: string;
			/** Expected Run Revision */
			expected_run_revision: number;
			/** Base Branch */
			base_branch: string;
		};
		/** PreparedImplementationAttempt */
		PreparedImplementationAttempt: {
			attempt: components['schemas']['ExecutionAttemptRead'];
			request: components['schemas']['ImplementationRequest'];
			/** Run Revision */
			run_revision: number;
			/** Created */
			created: boolean;
		};
		/** ProjectList */
		ProjectList: {
			/** Items */
			items: components['schemas']['ProjectRead'][];
			/** Total Count */
			total_count: number;
		};
		/** ProjectRead */
		ProjectRead: {
			/** Name */
			name: string;
			github?: components['schemas']['GitHubProjectConnection'] | null;
			linear?: components['schemas']['LinearProjectConnection'] | null;
			/**
			 * Enabled
			 * @default true
			 */
			enabled: boolean;
			/**
			 * Created At
			 * Format: date-time
			 */
			created_at: string;
			/**
			 * Updated At
			 * Format: date-time
			 */
			updated_at: string;
			/**
			 * Id
			 * Format: uuid
			 */
			id: string;
			/** Revision */
			revision: number;
			/** Template Version */
			template_version: string | null;
			last_check: components['schemas']['ConnectionCheck'] | null;
			/** Repository */
			repository?: string | null;
			/** Linear Project Id */
			linear_project_id?: string | null;
			/** Github Connector Id */
			github_connector_id?: string | null;
			/** Linear Connector Id */
			linear_connector_id?: string | null;
			verification?: components['schemas']['VerificationConfig'] | null;
		};
		/** ProjectUpdate */
		ProjectUpdate: {
			/** Name */
			name: string;
			github?: components['schemas']['GitHubProjectConnection'] | null;
			linear?: components['schemas']['LinearProjectConnection'] | null;
			/**
			 * Enabled
			 * @default true
			 */
			enabled: boolean;
			/**
			 * Expected Revision
			 * @description Reject edits based on an outdated project version.
			 */
			expected_revision: number;
		};
		/**
		 * ProjectWrite
		 * @description A Hub project can exist before any external system is connected.
		 */
		ProjectWrite: {
			/** Name */
			name: string;
			github?: components['schemas']['GitHubProjectConnection'] | null;
			linear?: components['schemas']['LinearProjectConnection'] | null;
			/**
			 * Enabled
			 * @default true
			 */
			enabled: boolean;
		};
		/** PullObservation */
		PullObservation: {
			/** Number */
			number: number;
			/** Head Sha */
			head_sha: string;
			/** Base Sha */
			base_sha: string;
			/** Url */
			url: string;
			result: components['schemas']['VerificationResult'];
			run?: components['schemas']['RunSnapshot'] | null;
		};
		/** RunSnapshot */
		RunSnapshot: {
			/** Id */
			id: number;
			/** Attempt */
			attempt: number;
			/** Head Sha */
			head_sha: string;
			/** Status */
			status: string;
			/** Conclusion */
			conclusion?: string | null;
			/** Url */
			url: string;
			/** Jobs */
			jobs?: components['schemas']['JobSnapshot'][];
		};
		/** ScheduleConfigCreate */
		ScheduleConfigCreate: {
			/**
			 * Name
			 * @description Human-readable name of the schedule.
			 */
			name: string;
			/**
			 * Description
			 * @description Optional description of what this schedule does.
			 */
			description?: string | null;
			/**
			 * Task Func
			 * @description Dotted path to the task function to execute (e.g. 'tasks.send_report').
			 */
			task_func: string;
			/**
			 * Cron Expression
			 * @description Cron expression for time-based scheduling (e.g. '0 9 * * 1-5'). Mutually exclusive with interval_seconds.
			 */
			cron_expression?: string | null;
			/**
			 * Interval Seconds
			 * @description Fixed interval in seconds between executions. Mutually exclusive with cron_expression.
			 */
			interval_seconds?: number | null;
			/**
			 * Payload
			 * @description Arbitrary JSON payload passed to the task function as kwargs.
			 * @default {}
			 */
			payload: {
				[key: string]: unknown;
			};
			/**
			 * Enabled
			 * @description Whether this schedule is active and should be picked up by the dispatcher.
			 * @default true
			 */
			enabled: boolean;
			/**
			 * Start At
			 * @description Optional datetime after which the schedule becomes active.
			 */
			start_at?: string | null;
			/**
			 * End At
			 * @description Optional datetime after which the schedule is no longer executed.
			 */
			end_at?: string | null;
		};
		/** ScheduleConfigPatch */
		ScheduleConfigPatch: {
			/**
			 * Name
			 * @description Human-readable name of the schedule.
			 */
			name?: string | null;
			/**
			 * Description
			 * @description Optional description of what this schedule does.
			 */
			description?: string | null;
			/**
			 * Task Func
			 * @description Dotted path to the task function to execute.
			 */
			task_func?: string | null;
			/**
			 * Cron Expression
			 * @description Cron expression for time-based scheduling.
			 */
			cron_expression?: string | null;
			/**
			 * Interval Seconds
			 * @description Fixed interval in seconds between executions.
			 */
			interval_seconds?: number | null;
			/**
			 * Payload
			 * @description Arbitrary JSON payload passed to the task function as kwargs.
			 */
			payload?: {
				[key: string]: unknown;
			} | null;
			/**
			 * Enabled
			 * @description Whether this schedule is active.
			 */
			enabled?: boolean | null;
			/**
			 * Start At
			 * @description Optional datetime after which the schedule becomes active.
			 */
			start_at?: string | null;
			/**
			 * End At
			 * @description Optional datetime after which the schedule is no longer executed.
			 */
			end_at?: string | null;
		};
		/** ScheduleConfigPut */
		ScheduleConfigPut: {
			/**
			 * Name
			 * @description Human-readable name of the schedule.
			 */
			name: string;
			/**
			 * Description
			 * @description Optional description of what this schedule does.
			 */
			description?: string | null;
			/**
			 * Task Func
			 * @description Dotted path to the task function to execute (e.g. 'tasks.send_report').
			 */
			task_func: string;
			/**
			 * Cron Expression
			 * @description Cron expression for time-based scheduling (e.g. '0 9 * * 1-5'). Mutually exclusive with interval_seconds.
			 */
			cron_expression?: string | null;
			/**
			 * Interval Seconds
			 * @description Fixed interval in seconds between executions. Mutually exclusive with cron_expression.
			 */
			interval_seconds?: number | null;
			/**
			 * Payload
			 * @description Arbitrary JSON payload passed to the task function as kwargs.
			 * @default {}
			 */
			payload: {
				[key: string]: unknown;
			};
			/**
			 * Enabled
			 * @description Whether this schedule is active and should be picked up by the dispatcher.
			 * @default true
			 */
			enabled: boolean;
			/**
			 * Start At
			 * @description Optional datetime after which the schedule becomes active.
			 */
			start_at?: string | null;
			/**
			 * End At
			 * @description Optional datetime after which the schedule is no longer executed.
			 */
			end_at?: string | null;
		};
		/** ScheduleConfigRead */
		ScheduleConfigRead: {
			/**
			 * Name
			 * @description Human-readable name of the schedule.
			 */
			name: string;
			/**
			 * Description
			 * @description Optional description of what this schedule does.
			 */
			description?: string | null;
			/**
			 * Task Func
			 * @description Dotted path to the task function to execute (e.g. 'tasks.send_report').
			 */
			task_func: string;
			/**
			 * Cron Expression
			 * @description Cron expression for time-based scheduling (e.g. '0 9 * * 1-5'). Mutually exclusive with interval_seconds.
			 */
			cron_expression?: string | null;
			/**
			 * Interval Seconds
			 * @description Fixed interval in seconds between executions. Mutually exclusive with cron_expression.
			 */
			interval_seconds?: number | null;
			/**
			 * Payload
			 * @description Arbitrary JSON payload passed to the task function as kwargs.
			 * @default {}
			 */
			payload: {
				[key: string]: unknown;
			};
			/**
			 * Enabled
			 * @description Whether this schedule is active and should be picked up by the dispatcher.
			 * @default true
			 */
			enabled: boolean;
			/**
			 * Start At
			 * @description Optional datetime after which the schedule becomes active.
			 */
			start_at?: string | null;
			/**
			 * End At
			 * @description Optional datetime after which the schedule is no longer executed.
			 */
			end_at?: string | null;
			/**
			 * Created At
			 * Format: date-time
			 */
			created_at: string;
			/**
			 * Updated At
			 * Format: date-time
			 */
			updated_at: string;
			/**
			 * Id
			 * Format: uuid
			 */
			id: string;
			/**
			 * Last Run At
			 * @description Timestamp of the most recent execution.
			 */
			last_run_at: string | null;
			/**
			 * Next Run At
			 * @description Timestamp of the next scheduled execution.
			 */
			next_run_at: string | null;
		};
		/** ScheduleJobCreate */
		ScheduleJobCreate: {
			/**
			 * Name
			 * @description The name of the schedule job.
			 */
			name: string;
			/**
			 * Schedule Config Id
			 * @description Reference to the schedule config that triggered this job execution.
			 */
			schedule_config_id?: string | null;
			/**
			 * Dispatcher Run Id
			 * @description Reference to the dispatcher run that executed this job. Allows grouping multiple schedule jobs under a single dispatcher run for better traceability.
			 */
			dispatcher_run_id?: string | null;
			/** @description Execution status of the schedule. */
			status: components['schemas']['ScheduleJobStatus'];
			/**
			 * Started At
			 * Format: date-time
			 * @description Timestamp when the task execution started.
			 */
			started_at: string;
			/**
			 * Finished At
			 * @description Timestamp when the task execution finished.
			 */
			finished_at?: string | null;
			/**
			 * Payload
			 * @description Snapshot of the payload used during execution.
			 */
			payload?: {
				[key: string]: unknown;
			};
			/**
			 * Error Message
			 * @description Error message if the task execution failed.
			 */
			error_message?: string | null;
		};
		/** ScheduleJobPatch */
		ScheduleJobPatch: {
			/**
			 * Name
			 * @description The name of the schedule job.
			 */
			name?: string | null;
			/**
			 * Schedule Config Id
			 * @description Reference to the schedule config.
			 */
			schedule_config_id?: string | null;
			/**
			 * Dispatcher Run Id
			 * @description Reference to the dispatcher run.
			 */
			dispatcher_run_id?: string | null;
			/** @description Execution status of the schedule. */
			status?: components['schemas']['ScheduleJobStatus'] | null;
			/**
			 * Started At
			 * @description Timestamp when the task execution started.
			 */
			started_at?: string | null;
			/**
			 * Finished At
			 * @description Timestamp when the task execution finished.
			 */
			finished_at?: string | null;
			/**
			 * Payload
			 * @description Snapshot of the payload used during execution.
			 */
			payload?: {
				[key: string]: unknown;
			} | null;
			/**
			 * Error Message
			 * @description Error message if the task execution failed.
			 */
			error_message?: string | null;
		};
		/** ScheduleJobPut */
		ScheduleJobPut: {
			/**
			 * Name
			 * @description The name of the schedule job.
			 */
			name: string;
			/**
			 * Schedule Config Id
			 * @description Reference to the schedule config that triggered this job execution.
			 */
			schedule_config_id?: string | null;
			/**
			 * Dispatcher Run Id
			 * @description Reference to the dispatcher run that executed this job. Allows grouping multiple schedule jobs under a single dispatcher run for better traceability.
			 */
			dispatcher_run_id?: string | null;
			/** @description Execution status of the schedule. */
			status: components['schemas']['ScheduleJobStatus'];
			/**
			 * Started At
			 * Format: date-time
			 * @description Timestamp when the task execution started.
			 */
			started_at: string;
			/**
			 * Finished At
			 * @description Timestamp when the task execution finished.
			 */
			finished_at?: string | null;
			/**
			 * Payload
			 * @description Snapshot of the payload used during execution.
			 */
			payload?: {
				[key: string]: unknown;
			};
			/**
			 * Error Message
			 * @description Error message if the task execution failed.
			 */
			error_message?: string | null;
		};
		/** ScheduleJobRead */
		ScheduleJobRead: {
			/**
			 * Name
			 * @description The name of the schedule job.
			 */
			name: string;
			/**
			 * Schedule Config Id
			 * @description Reference to the schedule config that triggered this job execution.
			 */
			schedule_config_id?: string | null;
			/**
			 * Dispatcher Run Id
			 * @description Reference to the dispatcher run that executed this job. Allows grouping multiple schedule jobs under a single dispatcher run for better traceability.
			 */
			dispatcher_run_id?: string | null;
			/** @description Execution status of the schedule. */
			status: components['schemas']['ScheduleJobStatus'];
			/**
			 * Started At
			 * Format: date-time
			 * @description Timestamp when the task execution started.
			 */
			started_at: string;
			/**
			 * Finished At
			 * @description Timestamp when the task execution finished.
			 */
			finished_at?: string | null;
			/**
			 * Payload
			 * @description Snapshot of the payload used during execution.
			 */
			payload?: {
				[key: string]: unknown;
			};
			/**
			 * Error Message
			 * @description Error message if the task execution failed.
			 */
			error_message?: string | null;
			/**
			 * Created At
			 * Format: date-time
			 */
			created_at: string;
			/**
			 * Updated At
			 * Format: date-time
			 */
			updated_at: string;
			/**
			 * Id
			 * Format: uuid
			 */
			id: string;
		};
		/**
		 * ScheduleJobStatus
		 * @enum {string}
		 */
		ScheduleJobStatus: 'pending' | 'success' | 'failure';
		/** SchedulerDefaults */
		SchedulerDefaults: {
			/**
			 * Global Timeout Seconds
			 * @description Default global timeout for scheduled tasks in seconds
			 * @default 300
			 */
			GLOBAL_TIMEOUT_SECONDS: number;
			/**
			 * Global Timeout Buffer
			 * @description Buffer time to subtract from the global timeout to ensure tasks complete within limits in seconds
			 * @default 30
			 */
			GLOBAL_TIMEOUT_BUFFER: number;
			/**
			 * Max Concurrent Tasks
			 * @description Maximum number of concurrent tasks that can be scheduled
			 * @default 10
			 */
			MAX_CONCURRENT_TASKS: number;
			/**
			 * Max Retry Attempts
			 * @description Maximum number of retry attempts for failed tasks
			 * @default 3
			 */
			MAX_RETRY_ATTEMPTS: number;
			/**
			 * Max Dispatch Limit
			 * @description Maximum number of schedules or retry jobs to fetch in a single tick
			 * @default 200
			 */
			MAX_DISPATCH_LIMIT: number;
		};
		/** SystemConfigCreate */
		SystemConfigCreate: {
			/**
			 * Name
			 * @description The name of the system_config.
			 */
			name: string;
			/**
			 * Data
			 * @description The data of the system_config.
			 */
			data?: {
				[key: string]: unknown;
			} | null;
		};
		/** SystemConfigPatch */
		SystemConfigPatch: {
			/**
			 * Name
			 * @description The name of the system_config.
			 */
			name?: string | null;
			/**
			 * Data
			 * @description The data of the system_config.
			 */
			data?: {
				[key: string]: unknown;
			} | null;
		};
		/** SystemConfigPut */
		SystemConfigPut: {
			/**
			 * Name
			 * @description The name of the system_config.
			 */
			name: string;
			/**
			 * Data
			 * @description The data of the system_config.
			 */
			data?: {
				[key: string]: unknown;
			} | null;
		};
		/** SystemConfigRead */
		SystemConfigRead: {
			/**
			 * Name
			 * @description The name of the system_config.
			 */
			name: string;
			/**
			 * Data
			 * @description The data of the system_config.
			 */
			data?: {
				[key: string]: unknown;
			} | null;
			/**
			 * Created At
			 * Format: date-time
			 */
			created_at: string;
			/**
			 * Updated At
			 * Format: date-time
			 */
			updated_at: string;
			/**
			 * Id
			 * Format: uuid
			 */
			id: string;
		};
		/** TaskSpecResponse */
		TaskSpecResponse: {
			/** Name */
			name: string;
			/** Description */
			description: string;
			/** Payload Schema */
			payload_schema?: {
				[key: string]: unknown;
			} | null;
		};
		/** TemplateRead */
		TemplateRead: {
			/**
			 * Id
			 * @enum {string}
			 */
			id: 'python-uv' | 'node-npm';
			/** Name */
			name: string;
			/** Version */
			version: string;
			/** Changelog */
			changelog: string;
			/** Required Jobs */
			required_jobs: string[];
			/** Filename */
			filename: string;
			/** Content */
			content: string;
		};
		/** ValidationError */
		ValidationError: {
			/** Location */
			loc: (string | number)[];
			/** Message */
			msg: string;
			/** Error Type */
			type: string;
			/** Input */
			input?: unknown;
			/** Context */
			ctx?: Record<string, never>;
		};
		/** VerificationConfig */
		VerificationConfig: {
			/**
			 * Workflow
			 * @description Workflow filename, not display name.
			 */
			workflow: string;
			/**
			 * Required Jobs
			 * @description Exact GitHub Actions job names.
			 */
			required_jobs: string[];
			/**
			 * Event
			 * @default pull_request
			 * @constant
			 */
			event: 'pull_request';
		};
		/** VerificationResult */
		VerificationResult: {
			status: components['schemas']['VerificationStatus'];
			/** Reason */
			reason: string;
			/** Missing Jobs */
			missing_jobs?: string[];
			/** Unsuccessful Jobs */
			unsuccessful_jobs?: string[];
		};
		/**
		 * VerificationStatus
		 * @enum {string}
		 */
		VerificationStatus: 'passed' | 'waiting' | 'failed' | 'blocked' | 'closed';
	};
	responses: never;
	parameters: never;
	requestBodies: never;
	headers: never;
	pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
	root__get: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': unknown;
				};
			};
		};
	};
	health_api_health_get: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': unknown;
				};
			};
		};
	};
	deep_health_check_api_health_deep_get: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': unknown;
				};
			};
		};
	};
	get_connectors_api_v1_connectors_get: {
		parameters: {
			query?: {
				/** @description offset for pagination */
				offset?: number;
				/** @description limit for pagination */
				limit?: number;
				/** @description Filter query parameter (name) */
				name?: string | null;
				/** @description Filter query parameter (provider) */
				provider?: string | null;
				/** @description Filter query parameter (enabled) */
				enabled?: boolean | null;
				/**
				 * @description **Order by options:**
				 *
				 *     * `name`
				 *     * `created_at`
				 *     * `updated_at`
				 *     * `id`
				 *
				 *     **Usage:**
				 *     * Prefix with `-` for descending order (e.g., `-title`).
				 *     * Multiple fields can be separated by commas (e.g., `-created_at,title`).
				 *     * **Default:** `-created_at`
				 */
				order_by?: string | null;
			};
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['PaginatedList_ConnectorRead_'];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	create_connector_api_v1_connectors_post: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['ConnectorCreate'];
			};
		};
		responses: {
			/** @description Successful Response */
			201: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ConnectorRead'];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	get_connector_api_v1_connectors__connector_id__get: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				connector_id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ConnectorRead'];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	put_connector_api_v1_connectors__connector_id__put: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				connector_id: string;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['ConnectorPut'];
			};
		};
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ConnectorRead'];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	delete_connector_api_v1_connectors__connector_id__delete: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				connector_id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['DeleteResponse'];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	patch_connector_api_v1_connectors__connector_id__patch: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				connector_id: string;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['ConnectorPatch'];
			};
		};
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ConnectorRead'];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	inspect_pipeline_api_v1_pipelines_inspect_post: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['PipelineObservationConfig'];
			};
		};
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['PipelineObservation'];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	get_pipeline_observation_api_v1_pipelines_observations__schedule_id__get: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				schedule_id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['PipelineObservation'];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	list_pipeline_runs_api_v1_pipeline_runs_get: {
		parameters: {
			query?: {
				project_id?: string | null;
				offset?: number;
				limit?: number;
			};
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['PipelineRunList'];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	get_pipeline_run_api_v1_pipeline_runs__run_id__get: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				run_id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['PipelineRunRead'];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	list_execution_attempts_api_v1_pipeline_runs__run_id__attempts_get: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				run_id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ExecutionAttemptList'];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	renew_pipeline_run_lease_api_v1_pipeline_runs__run_id__lease_put: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				run_id: string;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['LeaseMutation'];
			};
		};
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['LeaseGrant'];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	acquire_pipeline_run_lease_api_v1_pipeline_runs__run_id__lease_post: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				run_id: string;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['LeaseRequest'];
			};
		};
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['LeaseGrant'];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	release_pipeline_run_lease_api_v1_pipeline_runs__run_id__lease_release_post: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				run_id: string;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['LeaseMutation'];
			};
		};
		responses: {
			/** @description Successful Response */
			204: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	prepare_implementation_attempt_api_v1_pipeline_runs__run_id__attempts_implementation_post: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				run_id: string;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['PrepareImplementationAttempt'];
			};
		};
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['PreparedImplementationAttempt'];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	list_projects_api_v1_projects_get: {
		parameters: {
			query?: {
				offset?: number;
				limit?: number;
			};
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ProjectList'];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	create_project_api_v1_projects_post: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['ProjectWrite'];
			};
		};
		responses: {
			/** @description Successful Response */
			201: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ProjectRead'];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	get_project_templates_api_v1_projects_templates_get: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['TemplateRead'][];
				};
			};
		};
	};
	import_project_schedule_api_v1_projects_import_schedule_post: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['ImportScheduleRequest'];
			};
		};
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ProjectRead'];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	get_project_api_v1_projects__project_id__get: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				project_id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ProjectRead'];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	update_project_api_v1_projects__project_id__put: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				project_id: string;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['ProjectUpdate'];
			};
		};
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ProjectRead'];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	delete_project_api_v1_projects__project_id__delete: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				project_id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			204: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	get_actionable_issue_api_v1_projects__project_id__issues_actionable_get: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				project_id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ActionableIssueSelection'];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	acquire_pipeline_run_api_v1_projects__project_id__runs_acquire_post: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				project_id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['PipelineRunAcquisition'];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	check_project_api_v1_projects__project_id__check_post: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				project_id: string;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['CheckRequest'];
			};
		};
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ConnectionCheck'];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	get_schedule_configs_api_v1_schedule_configs_get: {
		parameters: {
			query?: {
				/** @description offset for pagination */
				offset?: number;
				/** @description limit for pagination */
				limit?: number;
				/** @description Filter by name (case-insensitive substring) */
				name?: string | null;
				/** @description Filter by task function path (case-insensitive substring) */
				task_func?: string | null;
				/** @description Filter by enabled status */
				enabled?: boolean | null;
				/**
				 * @description **Order by options:**
				 *
				 *     * `name`: Sort by name
				 *     * `created_at`: Sort by creation time
				 *     * `updated_at`: Sort by update time
				 *     * `next_run_at`: Sort by next run time
				 *     * `last_run_at`: Sort by last run time
				 *     * `id`: Sort by ID
				 *
				 *     **Usage:**
				 *     * Prefix with `-` for descending order (e.g., `-title`).
				 *     * Multiple fields can be separated by commas (e.g., `-created_at,title`).
				 *     * **Default:** `-created_at`
				 */
				order_by?: string | null;
			};
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['PaginatedList_ScheduleConfigRead_'];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	create_schedule_config_api_v1_schedule_configs_post: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['ScheduleConfigCreate'];
			};
		};
		responses: {
			/** @description Successful Response */
			201: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ScheduleConfigRead'];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	get_schedule_config_api_v1_schedule_configs__schedule_config_id__get: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				schedule_config_id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ScheduleConfigRead'];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	put_schedule_config_api_v1_schedule_configs__schedule_config_id__put: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				schedule_config_id: string;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['ScheduleConfigPut'];
			};
		};
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ScheduleConfigRead'];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	delete_schedule_config_api_v1_schedule_configs__schedule_config_id__delete: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				schedule_config_id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['DeleteResponse'];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	patch_schedule_config_api_v1_schedule_configs__schedule_config_id__patch: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				schedule_config_id: string;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['ScheduleConfigPatch'];
			};
		};
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ScheduleConfigRead'];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	get_system_configs_api_v1_system_configs_get: {
		parameters: {
			query?: {
				/** @description offset for pagination */
				offset?: number;
				/** @description limit for pagination */
				limit?: number;
				/** @description Filter by name (case-insensitive substring) */
				name?: string | null;
				/**
				 * @description **Order by options:**
				 *
				 *     * `name`: Sort by name
				 *     * `created_at`: Sort by creation time
				 *     * `updated_at`: Sort by update time
				 *     * `id`: Sort by ID
				 *
				 *     **Usage:**
				 *     * Prefix with `-` for descending order (e.g., `-title`).
				 *     * Multiple fields can be separated by commas (e.g., `-created_at,title`).
				 *     * **Default:** `-created_at`
				 */
				order_by?: string | null;
			};
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['PaginatedList_SystemConfigRead_'];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	create_system_config_api_v1_system_configs_post: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['SystemConfigCreate'];
			};
		};
		responses: {
			/** @description Successful Response */
			201: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['SystemConfigRead'];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	get_system_config_api_v1_system_configs__system_config_id__get: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				system_config_id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['SystemConfigRead'];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	put_system_config_api_v1_system_configs__system_config_id__put: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				system_config_id: string;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['SystemConfigPut'];
			};
		};
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['SystemConfigRead'];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	delete_system_config_api_v1_system_configs__system_config_id__delete: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				system_config_id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['DeleteResponse'];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	patch_system_config_api_v1_system_configs__system_config_id__patch: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				system_config_id: string;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['SystemConfigPatch'];
			};
		};
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['SystemConfigRead'];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	get_schedule_jobs_api_v1_schedule_jobs_get: {
		parameters: {
			query?: {
				/** @description offset for pagination */
				offset?: number;
				/** @description limit for pagination */
				limit?: number;
				/** @description Filter by name (case-insensitive substring) */
				name?: string | null;
				/** @description Filter by execution status */
				status?: components['schemas']['ScheduleJobStatus'] | null;
				/** @description Filter by schedule configuration ID */
				schedule_config_id?: string | null;
				/** @description Filter by dispatcher run ID */
				dispatcher_run_id?: string | null;
				/** @description Filter by whether retry is needed */
				retry_need?: boolean | null;
				/**
				 * @description **Order by options:**
				 *
				 *     * `name`: Sort by name
				 *     * `status`: Sort by status
				 *     * `started_at`: Sort by execution start time
				 *     * `finished_at`: Sort by execution finish time
				 *     * `created_at`: Sort by creation time
				 *     * `updated_at`: Sort by update time
				 *     * `id`: Sort by ID
				 *
				 *     **Usage:**
				 *     * Prefix with `-` for descending order (e.g., `-title`).
				 *     * Multiple fields can be separated by commas (e.g., `-created_at,title`).
				 *     * **Default:** `-started_at`
				 */
				order_by?: string | null;
			};
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['PaginatedList_ScheduleJobRead_'];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	create_schedule_job_api_v1_schedule_jobs_post: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['ScheduleJobCreate'];
			};
		};
		responses: {
			/** @description Successful Response */
			201: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ScheduleJobRead'];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	get_schedule_job_api_v1_schedule_jobs__schedule_job_id__get: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				schedule_job_id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ScheduleJobRead'];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	put_schedule_job_api_v1_schedule_jobs__schedule_job_id__put: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				schedule_job_id: string;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['ScheduleJobPut'];
			};
		};
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ScheduleJobRead'];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	delete_schedule_job_api_v1_schedule_jobs__schedule_job_id__delete: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				schedule_job_id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['DeleteResponse'];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	patch_schedule_job_api_v1_schedule_jobs__schedule_job_id__patch: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				schedule_job_id: string;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['ScheduleJobPatch'];
			};
		};
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ScheduleJobRead'];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	trigger_dispatch_api_v1_dispatchers_trigger_post: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: {
			content: {
				'application/json': components['schemas']['SchedulerDefaults'] | null;
			};
		};
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['DispatchResponse'];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	get_task_specs_api_v1_tasks_specs_get: {
		parameters: {
			query?: {
				/** @description Filter task specs by name (case-insensitive substring) */
				name?: string | null;
			};
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['TaskSpecResponse'][];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
}
